/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://jitpack.io")
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
        url = uri("https://repo.maven.apache.org/maven2/")
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    implementation("org.bstats:bstats-bukkit:2.2.1")
    implementation("mysql:mysql-connector-java:5.1.49")
    implementation("com.zaxxer:HikariCP:4.0.3")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7.0")
    compileOnly("me.clip:placeholderapi:2.10.0")
    compileOnly("com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT")
    compileOnly(fileTree("lib"))

}

group = "GeekCodePlus"
version = "3.1"
description = "GeekCodePlus"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
